spring:
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
  devtools:
    livereload:
      enabled: false
    freemarker:
      cache: true
  datasource:
    url: jdbc:mariadb://localhost:3306/sjyprj_db?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 199441
    timeBetweenEvictionRunsMillis: 60000
    connection-test-query: SELECT 1
    test-while-idle: true
    test-on-borrow: true
    validationQuery: SELECT 1
    max-active: 100
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      # create create-drop update validate none
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  servlet:
    multipart:
      maxFileSize: 50000MB
      maxRequestSize: 5000MB


server:
  port: 9088
  tomcat:
    max-connections: 1000
    max-threads: 500
    min-spare-threads: 10
